config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'

  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
  get 'say/hello'
  get 'say/goodbye'
  root to: "home#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/office.rb
class Office < ApplicationRecord
    validates :building_name, presence: true
    validates :floor_number, :room_number, numericality: { only_integer: true }, presence: true
    validates :room_number, length: {minimum: 3, maximum: 8}
    has_one :teacher
    # fields: "office.building_name", "office.floor_number", "office.room_number"
    def office_location
        "#{building_name} #{room_number}"
    end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  def index
    @offices = Office.all
  end

  # GET /offices/1
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # Search Offices
  def search
    @offices = Office.where("room_number like ?", "%#{params[:query]}%")
    render :index
  end

  # GET /offices/1/destroy
  def destroy
    @office.destroy
    redirect_to offices_url, notice: 'Office was successfully destroyed'
    end

  # POST /offices
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new, status: :unprocessable_entity }
	      format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end  
  end

  # PATCH/PUT /offices/1
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /offices/1
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed' }
      format.json { head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def office_params
      params.require(:office).permit(:building_name, :floor_number, :room_number)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_name %>
    <%= form.text_field :building_name %>
  </div>

  <div class="field">
    <%= form.label :floor_number %>
    <%= form.number_field :floor_number %>
  </div>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>MSU Denver Offices</h1>

<table>
  <thead>
    <tr>
      <th>Building</th>
      <th>Floor</th>
      <th>Room</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.building_name %></td>
        <td><%= office.floor_number %></td>
        <td><%= office.room_number %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= button_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag(search_offices_url, method: "get") do %>
  <%= label_tag(:query, "Search by Office Room Number:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<%= link_to 'New Office', new_office_path %> |
<%= link_to 'Teachers', Teacher %> |
<%= link_to 'Courses', Course %> |
<%= link_to 'Sections', Section %> |
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/offices/new.html.erb
<h1>New Teacher Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<h1>OFFICE INFO<h1>

<p>
  <strong>Building:</strong>
  <%= @office.building_name %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @office.floor_number %>
</p>

<p>
  <strong>Room:</strong>
  <%= @office.room_number %>
</p>

<br>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>