config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'

  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
  get 'say/hello'
  get 'say/goodbye'
  root to: "home#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  validates :year, numericality: { only_integer: true }, length: {is: 4, message: "Not a Valid Year"},
   presence: true
  validates :semester, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "Spring - Summer - Fall" }
  belongs_to :course
  # fields: "section.year", "section.semester", "course.prefix_and_number"
  def semester_year
    "#{semester} #{year}"
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  def index
    @sections = Section.all
  end

  # GET /sections/1
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  #Search sections
  def search
    @sections = Section.where("year like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

    # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section/1
  # DELETE /section/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:year, :semester, :course_id)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="control-group">
  <div class="controls">
    <%= form.label :year %>
    <%= form.select(:year, options_for_select([2019, 2020, 2021, 2022])) %>
  </div>
</div>

  <div class="radio">
    <%= form.radio_button :semester, "Fall" %>
    <%= form.label :semester, "Fall" %>
    <%= form.radio_button :semester, "Spring" %>
    <%= form.label :semester, "Spring" %>
    <%= form.radio_button :semester, "Summer" %>
    <%= form.label :semester, "Summer" %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :prefix_and_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>MSU Denver Sections</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Semester</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.year %></td>
        <td><%= section.semester %></td>
        <td><%= section.course.prefix_and_number %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= button_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag(search_sections_url, method: "get") do %>
  <%= label_tag(:query, "Search by Section Year:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<%= link_to 'New Section', new_section_path %> |
<%= link_to 'Teachers', Teacher %> |
<%= link_to 'Offices', Office %> |
<%= link_to 'Courses', Course %> |
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @section.year %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course.prefix_and_number %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>