config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'

  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :courses do
    collection do
      get 'search'
    end
  end
  resources :offices do
    collection do
      get 'search'
    end
  end
  resources :teachers do
    collection do
      get 'search'
    end
  end
  get 'say/hello'
  get 'say/goodbye'
  root to: "home#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :first_name, :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "No Numbers!" }
  validates :nine_hundred, numericality: { only_integer: true }, length: {is: 9, message: "Must be 9 Numbers"},
   presence: true, uniqueness: true
  validates :email, email: true
  validates :office, presence: true
  belongs_to :office
  has_many :courses
  def full_teacher_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  def index
    @teachers = Teacher.all
    #@teachers = Teacher.search(params[:search])
  end

  # GET /teachers/1
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  #Search teachers
  def search
    @teachers = Teacher.where("last_name like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teacher/1
  # DELETE /teacher/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :nine_hundred, :email, :office_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :nine_hundred %>
    <%= form.number_field :nine_hundred %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :office_id %>
    <%= form.text_field :office_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>MSU Denver Teachers</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>ID</th>
      <th>Email</th>
      <th>Office</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.nine_hundred %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to teacher.office.office_location, Office.find(teacher.office_id) %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= button_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= form_tag(search_teachers_url, method: "get") do %>
  <%= label_tag(:query, "Search by Teacher Last Name:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag "Search", :name => nil %>
<% end %>


<br>


          <%= link_to 'New Teacher', new_teacher_path %> |
          <%= link_to 'Offices', Office %> |
          <%= link_to 'Courses', Course %> |
          <%= link_to 'Sections', Section %> |
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/teachers/new.html.erb
<h1>New Teacher Addition</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>PROFESSOR INFO<h1>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Nine hundred:</strong>
  <%= @teacher.nine_hundred %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Office:</strong>
  <%= @teacher.office_id %>
</p>

<br>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>